# Generated by Django 5.1.1 on 2024-09-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('resource_type', models.CharField(max_length=50)),
                ('file_link', models.URLField()),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
    ]
